// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationMBegyn.Data;

namespace WebApplicationMBegyn.Migrations
{
    [DbContext(typeof(WebApplicationMBegynContext))]
    [Migration("20200901061420_firstinit5")]
    partial class firstinit5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplicationMBegyn.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AverageGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NbOfCourses")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentID");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            Address = "807th Flower Street, 90017 Los Angeles",
                            Age = 21,
                            AverageGrade = "B+",
                            FirstName = "John",
                            LastName = "Doe",
                            NbOfCourses = 8,
                            PhoneNumber = "332358797744"
                        },
                        new
                        {
                            StudentID = 2,
                            Address = "1400 Malcolm AVE, 90025 Los Angeles",
                            Age = 24,
                            AverageGrade = "B",
                            FirstName = "Susie",
                            LastName = "Dos Santos",
                            NbOfCourses = 5,
                            PhoneNumber = "4875329921"
                        });
                });

            modelBuilder.Entity("WebApplicationMBegyn.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NbOfClasses")
                        .HasColumnType("int");

                    b.Property<int>("NbOfTeachingExperience")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherID");

                    b.ToTable("Teacher");

                    b.HasData(
                        new
                        {
                            TeacherID = 1,
                            Address = "1250 W 50th Street, 90014 Los Angeles",
                            Age = 43,
                            FirstName = "Brendon",
                            LastName = "Waner",
                            NbOfClasses = 5,
                            NbOfTeachingExperience = 8,
                            PhoneNumber = "6325874488"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
